# Generated by Django 5.1.6 on 2025-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_continoustask_startingdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedtask",
            name="endDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="fixedtask",
            name="startingDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="progressdates",
            name="endDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="progressdates",
            name="startDate",
            field=models.DateTimeField(),
        ),
    ]
