# Generated by Django 5.1.6 on 2025-03-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_fixedtask_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="stopProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stopped_at", models.DateTimeField(auto_now_add=True)),
                ("task_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="progressdates",
            name="isStoped",
            field=models.BooleanField(default=False),
        ),
    ]
