# Generated by Django 5.1.6 on 2025-03-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_stopprogress_progressdates_isstoped"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progressdates",
            old_name="isStoped",
            new_name="isStopped",
        ),
    ]
